name: Universal CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Engine
      run: make engine_build

    - name: Load/Test the Engine
      run: make engine_test_workflow

    - name: Setup Underseer VEnv
      run: make underseer_prep_env

    - name: Setup Overseer VENV
      run: make overseer_prep_env

    - name: Start Overseer in the background
      run: setsid make overseer_start

    - name: Check for Overseer webpage
      run: make overseer_test_workflow

    - name: Build Underseer
      run: make underseer_build

    - name: Run Underseer
      run: make underseer_run &

    - name: Stop Everything
      continue-on-error: true
      run: make universal_stop
