name: Universal build run test (excluding WUI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v4

    - name: run universal_test_ghworkflow.sh
      run: ./scripts/universal_test_ghworkflow.sh
