name: Universal CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Engine
      run: make engine_build

    - name: Load Engine
      run: make engine_load

    - name: Setup Agent VEnv
      run: make agent__prep_env

    - name: Setup Overseer VENV
      run: make overseer_prep_env

    - name: Start Overseer in the background
      run: make overseer_run &

    - name: Check for Overseer webpage
      run: make overseer_test_workflow

    - name: Build Agent
      run: make agent_freeze

    - name: Run Agent
      run: make ./bergamot-agent &

    - name: Let Agent Cook
      run: sleep 5

    - name: Stop Everything
      continue-on-error: true
      run: make universal_stop
